name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for advanced Docker build capabilities)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/automated-daily-url-request:latest .

    # Step 5: Push the Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/automated-daily-url-request:latest